
### Fiind a partiuclar user with given ID
GET http://localhost:3000/auth/2


###Find all users with given email
GET http://localhost:3000/auth?email=asda@qwq.com


### Delete user with id
DELETE http://localhost:3000/auth/1


### Update user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
	"password" :"updated-password"
}



### Create a new user

POST http://localhost:3000/auth/signup
content-type: application/json

{ "email" : "admin@admin.com", "password" : "admin" }




### Sigin a new user

POST http://localhost:3000/auth/signin
content-type: application/json

{ "email" : "admin@admin.com", "password" : "admin" }


### Get recent sing in
GET http://localhost:3000/auth/whoami


### Sigin a new user

POST http://localhost:3000/auth/signout
